-- MySQL Script generated by MySQL Workbench
-- mié 01 feb 2017 11:33:47 VET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Logicargo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Logicargo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Logicargo` DEFAULT CHARACTER SET utf8 ;
USE `Logicargo` ;

-- -----------------------------------------------------
-- Table `Logicargo`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `cod_Area` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `Pais_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Estado_Pais1_idx` (`Pais_id` ASC),
  CONSTRAINT `fk_Estado_Pais1`
    FOREIGN KEY (`Pais_id`)
    REFERENCES `Logicargo`.`Pais` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Ciudad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `Estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ciudad_Estado1_idx` (`Estado_id` ASC),
  CONSTRAINT `fk_Ciudad_Estado1`
    FOREIGN KEY (`Estado_id`)
    REFERENCES `Logicargo`.`Estado` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(60) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `segundo_nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `segundo_apellido` VARCHAR(45) NULL,
  `rol` VARCHAR(45) NULL,
  `fecha_Nac` DATE NOT NULL,
  `cedula` INT NOT NULL,
  `Ciudad_id` INT NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Persona_Ciudad1_idx` (`Ciudad_id` ASC),
  CONSTRAINT `fk_Persona_Ciudad1`
    FOREIGN KEY (`Ciudad_id`)
    REFERENCES `Logicargo`.`Ciudad` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Sede` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(250) NOT NULL,
  `Ciudad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Sede_Ciudad1_idx` (`Ciudad_id` ASC),
  CONSTRAINT `fk_Sede_Ciudad1`
    FOREIGN KEY (`Ciudad_id`)
    REFERENCES `Logicargo`.`Ciudad` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Centro_Distribucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Centro_Distribucion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(250) NOT NULL,
  `Sede_id` INT NOT NULL,
  `Ciudad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Centro_Distribucion_Sede1_idx` (`Sede_id` ASC),
  INDEX `fk_Centro_Distribucion_Ciudad1_idx` (`Ciudad_id` ASC),
  CONSTRAINT `fk_Centro_Distribucion_Sede1`
    FOREIGN KEY (`Sede_id`)
    REFERENCES `Logicargo`.`Sede` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Centro_Distribucion_Ciudad1`
    FOREIGN KEY (`Ciudad_id`)
    REFERENCES `Logicargo`.`Ciudad` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Tipo_Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Tipo_Empleado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Empleado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NULL,
  `Persona_id` INT NOT NULL,
  `Centro_Distribucion_id` INT NOT NULL,
  `Tipo_Empleado_id` INT NOT NULL,
  `Jefe_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Empleado_Persona1_idx` (`Persona_id` ASC),
  INDEX `fk_Empleado_Centro_Distribucion1_idx` (`Centro_Distribucion_id` ASC),
  INDEX `fk_Empleado_Tipo_Empleado1_idx` (`Tipo_Empleado_id` ASC),
  INDEX `fk_Empleado_Empleado1_idx` (`Jefe_id` ASC),
  CONSTRAINT `fk_Empleado_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `Logicargo`.`Persona` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Empleado_Centro_Distribucion1`
    FOREIGN KEY (`Centro_Distribucion_id`)
    REFERENCES `Logicargo`.`Centro_Distribucion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Empleado_Tipo_Empleado1`
    FOREIGN KEY (`Tipo_Empleado_id`)
    REFERENCES `Logicargo`.`Tipo_Empleado` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Empleado_Empleado1`
    FOREIGN KEY (`Jefe_id`)
    REFERENCES `Logicargo`.`Empleado` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Tipo_Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Tipo_Vehiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Estado_Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Estado_Vehiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Vehiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `placa` INT NULL,
  `maxCapPaq` INT NOT NULL,
  `minCapPaq` INT NOT NULL,
  `carga` VARCHAR(45) NOT NULL,
  `anio` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `Centro_Distribucion_id` INT NOT NULL,
  `Tipo_Vehiculo_id` INT NULL,
  `Estado_Vehiculo_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Vehiculo_Centro_Distribucion1_idx` (`Centro_Distribucion_id` ASC),
  INDEX `fk_Vehiculo_Tipo_Vehiculo1_idx` (`Tipo_Vehiculo_id` ASC),
  INDEX `fk_Vehiculo_Estado_Vehiculo1_idx` (`Estado_Vehiculo_id` ASC),
  CONSTRAINT `fk_Vehiculo_Centro_Distribucion1`
    FOREIGN KEY (`Centro_Distribucion_id`)
    REFERENCES `Logicargo`.`Centro_Distribucion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Vehiculo_Tipo_Vehiculo1`
    FOREIGN KEY (`Tipo_Vehiculo_id`)
    REFERENCES `Logicargo`.`Tipo_Vehiculo` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Vehiculo_Estado_Vehiculo1`
    FOREIGN KEY (`Estado_Vehiculo_id`)
    REFERENCES `Logicargo`.`Estado_Vehiculo` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Paquete` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `peso` VARCHAR(45) NOT NULL,
  `volumen` VARCHAR(45) NOT NULL,
  `fragilidad` TINYINT(1) NOT NULL,
  `prioridad` TINYINT(1) NOT NULL,
  `Centro_Distribucion_idEmisor` INT NULL,
  `Centro_Distribucion_idReceptor` INT NULL,
  `Persona_idEmisor` INT NULL,
  `Persona_idReceptor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Paquete_Centro_Distribucion1_idx` (`Centro_Distribucion_idEmisor` ASC),
  INDEX `fk_Paquete_Centro_Distribucion2_idx` (`Centro_Distribucion_idReceptor` ASC),
  INDEX `fk_Paquete_Persona1_idx` (`Persona_idEmisor` ASC),
  INDEX `fk_Paquete_Persona2_idx` (`Persona_idReceptor` ASC),
  CONSTRAINT `fk_Paquete_Centro_Distribucion1`
    FOREIGN KEY (`Centro_Distribucion_idEmisor`)
    REFERENCES `Logicargo`.`Centro_Distribucion` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Paquete_Centro_Distribucion2`
    FOREIGN KEY (`Centro_Distribucion_idReceptor`)
    REFERENCES `Logicargo`.`Centro_Distribucion` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Paquete_Persona1`
    FOREIGN KEY (`Persona_idEmisor`)
    REFERENCES `Logicargo`.`Persona` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Paquete_Persona2`
    FOREIGN KEY (`Persona_idReceptor`)
    REFERENCES `Logicargo`.`Persona` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Itinerario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Itinerario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firma_Conf` TINYINT(1) NULL,
  `aviso_Notificacion` TINYINT(1) NULL,
  `Vehiculo_id` INT NULL,
  `Paquete_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Itinerario_Paquete1_idx` (`Paquete_id` ASC),
  INDEX `fk_Itinerario_Vehiculo1_idx` (`Vehiculo_id` ASC),
  CONSTRAINT `fk_Itinerario_Vehiculo1`
    FOREIGN KEY (`Vehiculo_id`)
    REFERENCES `Logicargo`.`Vehiculo` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Itinerario_Paquete1`
    FOREIGN KEY (`Paquete_id`)
    REFERENCES `Logicargo`.`Paquete` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Tipo_telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Tipo_telefono` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Telefono_Centro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Telefono_Centro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `Centro_Distribucion_id` INT NOT NULL,
  `Tipo_telefono_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Telefono_Centro_Centro_Distribucion1_idx` (`Centro_Distribucion_id` ASC),
  INDEX `fk_Telefono_Centro_Tipo_telefono1_idx` (`Tipo_telefono_id` ASC),
  CONSTRAINT `fk_Telefono_Centro_Centro_Distribucion1`
    FOREIGN KEY (`Centro_Distribucion_id`)
    REFERENCES `Logicargo`.`Centro_Distribucion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Telefono_Centro_Tipo_telefono1`
    FOREIGN KEY (`Tipo_telefono_id`)
    REFERENCES `Logicargo`.`Tipo_telefono` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Telefono_Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Telefono_Persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `Persona_id` INT NOT NULL,
  `Tipo_telefono_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Telefono_Persona_Persona1_idx` (`Persona_id` ASC),
  INDEX `fk_Telefono_Persona_Tipo_telefono1_idx` (`Tipo_telefono_id` ASC),
  CONSTRAINT `fk_Telefono_Persona_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `Logicargo`.`Persona` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Telefono_Persona_Tipo_telefono1`
    FOREIGN KEY (`Tipo_telefono_id`)
    REFERENCES `Logicargo`.`Tipo_telefono` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Telefono_Sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Telefono_Sede` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `Sede_id` INT NOT NULL,
  `Tipo_telefono_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Telefono_Sede_Sede1_idx` (`Sede_id` ASC),
  INDEX `fk_Telefono_Sede_Tipo_telefono1_idx` (`Tipo_telefono_id` ASC),
  CONSTRAINT `fk_Telefono_Sede_Sede1`
    FOREIGN KEY (`Sede_id`)
    REFERENCES `Logicargo`.`Sede` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Telefono_Sede_Tipo_telefono1`
    FOREIGN KEY (`Tipo_telefono_id`)
    REFERENCES `Logicargo`.`Tipo_telefono` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Historico_Paquete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Historico_Paquete` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fechaHora` DATETIME NOT NULL,
  `estatusPaquete` VARCHAR(150) NOT NULL,
  `Paquete_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Historico_Paquete_Paquete1_idx` (`Paquete_id` ASC),
  CONSTRAINT `fk_Historico_Pauete_Paquete1`
    FOREIGN KEY (`Paquete_id`)
    REFERENCES `Logicargo`.`Paquete` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Historico_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Historico_Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_Persona` INT NOT NULL,
  `fechaHora` DATETIME NOT NULL,
  `user` VARCHAR(60) NOT NULL,
  `rol` VARCHAR(60) NOT NULL,
  `accion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Logicargo`.`Vehiculo_has_Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Logicargo`.`Vehiculo_has_Empleado` (
  `id` INT NOT NULL UNIQUE AUTO_INCREMENT,
  `Vehiculo_id` INT NOT NULL,
  `Empleado_id` INT NOT NULL,
  `fechaAsignacion` DATE NOT NULL,
  INDEX `fk_Vehiculo_has_Empleado_Empleado1_idx` (`Empleado_id` ASC),
  INDEX `fk_Vehiculo_has_Empleado_Vehiculo1_idx` (`Vehiculo_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Vehiculo_has_Empleado_Vehiculo1`
    FOREIGN KEY (`Vehiculo_id`)
    REFERENCES `Logicargo`.`Vehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculo_has_Empleado_Empleado1`
    FOREIGN KEY (`Empleado_id`)
    REFERENCES `Logicargo`.`Empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
