insert into Sede values
(1, 'Amazonas', 'Amazonas', 1),
(2, 'Anzoategui', 'Anzoategui', 1),
(3, 'Apure', 'Apure', 1),
(4, 'Aragua', 'Aragua', 1),
(5, 'Barinas', 'Barinas', 1),
(6, 'Bolivar', 'Bolivar', 1),
(7, 'Carabobo', 'Carabobo', 1),
(8, 'Cojedes', 'Cojedes', 1),
(9, 'Delta Amacuro', 'Delta Amacuro', 1),
(10, 'Distrito Capital', 'Distrito Capital', 1),
(11, 'Falcon', 'Falcon', 1),
(12, 'Guarico', 'Guarico', 1),
(13, 'Lara', 'Lara', 1),
(14, 'Merida', 'Merida', 1),
(15, 'Miranda', 'Miranda', 1),
(16, 'Monagas', 'Monagas', 1),
(17, 'Nueva Esparta', 'Nueva Esparta', 1),
(18, 'Portuguesa', 'Portuguesa', 1),
(19, 'Sucre', 'Sucre', 1),
(20, 'Tachira', 'Tachira', 1),
(21, 'Trujillo', 'Trujillo', 1),
(22, 'Vargas', 'Vargas', 1),
(23, 'Yaracuy', 'Yaracuy', 1),
(24, 'Zulia', 'Zulia', 1);